vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        picture_file:
              # alias qui nous permet d'accéder à nos images depuis le navigateur
              uri_prefix: /uploads/members
              # Chemin vers le dossier de stockage
              upload_destination: '%kernel.project_dir%/public/uploads/members'
              namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # or any other namer listed above
        image_file:
                uri_prefix: /uploads/themes
                upload_destination: '%kernel.project_dir%/public/uploads/themes'

                inject_on_load: false
                delete_on_update: true
                delete_on_remove: true
   
